name: Build and Deploy to Azure App Service

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build Docker image
    - name: Build Docker image
      run: docker build -t bmi-app:${{ github.sha }} .

    # Log in to Azure Container Registry (ACR)
    - name: Log in to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login bmiserviceacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Push Docker image to ACR
    - name: Push Docker image to ACR
      run: docker push bmiserviceacr.azurecr.io/bmi-app:${{ github.sha }}

    # Infrastructure setup (first-time)
    - name: Create Azure infrastructure
      run: |
        az appservice plan create --name BMIAppService --resource-group bmi-service-app --sku B1
        az webapp create --resource-group bmi-service-app --plan MyAppServicePlan --name MyApp --deployment-container-image-name bmiserviceacr.azurecr.io/bmi-app:${{ github.sha }}

    # Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: BMIAppService 
        images: bmiserviceacr.azurecr.io/bmi-app:${{ github.sha }}